name: glacier-policy-app
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - bokeh=2.4.3
  - nbserverproxy
  - tornado
  - ipywidgets
  - graphviz
  - numpy
  - scipy
  - pandas
  - shapely
  - netcdf4
  - configobj
  - xarray
  - pyviz_comms
  - param
  - holoviews=1.15.1
  - jinja2
  - panel=0.14.0
  - parambokeh
  - ipympl
  - seaborn
  - pip:
    - joblib
    - progressbar2
    - jupyter-panel-proxy
